### ISSUE TITLE
[Bug]: Adapter stürzt immer wieder ab 

### ISSUE THREAD

**Issue by hotwin** [iobroker-community-adapters/ioBroker.chromecast#100]
### Contact Details

hotwin@gmx.net

### What happened?

A bug happened! Ich habe auf meinem ioBroker diesen Adapter neu installiert 
und musste festellen das der Adapter immer abstürzt 

### Adapter Version

2.3.1

### JS-Controller Version

0.0.0

### Node JS Version

12.22.6

### NPM Version

0.0.0

### Operating System

Ubuntu

### Relevant log output

```shell
chromecast.0
23249	2021-10-10 19:22:15.260	info	terminating with timeout

chromecast.0
23249	2021-10-10 19:22:13.758	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

chromecast.0
23249	2021-10-10 19:22:13.756	info	terminating

chromecast.0
23249	2021-10-10 19:22:13.754	info	Unload completed sucesfully

chromecast.0
23249	2021-10-10 19:22:13.754	info	Google home pierre - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.753	info	Tedt - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.751	info	Tv Eltern - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.750	info	Tv Eltern - Detached player

chromecast.0
23249	2021-10-10 19:22:13.748	info	Tv Eltern - Detached player

chromecast.0
23249	2021-10-10 19:22:13.746	info	Google Home PC Raum - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.744	info	Wohnzimmer - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.743	info	Wohnzimmer - Detached player

chromecast.0
23249	2021-10-10 19:22:13.742	info	Wohnzimmer - Detached player

chromecast.0
23249	2021-10-10 19:22:13.740	info	Pierre - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.738	info	Pierre - Detached player

chromecast.0
23249	2021-10-10 19:22:13.737	info	Pierre - Detached player

chromecast.0
23249	2021-10-10 19:22:13.734	info	Andrew - client disconnected

chromecast.0
23249	2021-10-10 19:22:13.730	info	Destroying chromecast scanner

chromecast.0
23249	2021-10-10 19:22:13.725	info	Unload triggered

chromecast.0
23249	2021-10-10 19:22:13.531	error	Cannot read property 'contentId' of undefined

chromecast.0
23249	2021-10-10 19:22:13.531	error	TypeError: Cannot read property 'contentId' of undefined at PersistentPlayer._playerStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58) at DefaultMediaReceiver.emit (events.js:314:20) at fn.onstatus (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10) at fn.emit (events.js:314:20) at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12) at fn.emit (events.js:326:22) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:314:20) at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10) at Client.emit (events.js:326:22)

chromecast.0
23249	2021-10-10 19:22:13.529	error	uncaught exception: Cannot read property 'contentId' of undefined

chromecast.0
23249	2021-10-10 19:22:13.315	info	Tv Eltern - Player joint

chromecast.0
23249	2021-10-10 19:22:13.313	info	Tv Eltern - Connected player

chromecast.0
23249	2021-10-10 19:22:13.310	info	Tv Eltern - Try to join player

chromecast.0
23249	2021-10-10 19:22:13.253	info	Pierre - Playing -

chromecast.0
23249	2021-10-10 19:22:13.191	info	Pierre - Player joint

chromecast.0
23249	2021-10-10 19:22:13.189	info	Pierre - Connected player

chromecast.0
23249	2021-10-10 19:22:13.186	info	Pierre - Try to join player

chromecast.0
23249	2021-10-10 19:22:13.181	info	Google home pierre - Connected client

chromecast.0
23249	2021-10-10 19:22:13.161	info	Tedt - Connected client

chromecast.0
23249	2021-10-10 19:22:13.155	info	Google Home PC Raum - Connected client

chromecast.0
23249	2021-10-10 19:22:13.149	info	Tv Eltern - Connected client

chromecast.0
23249	2021-10-10 19:22:13.142	info	Wohnzimmer - Player joint

chromecast.0
23249	2021-10-10 19:22:13.139	info	Wohnzimmer - Connected player

chromecast.0
23249	2021-10-10 19:22:13.134	info	Wohnzimmer - Try to join player

chromecast.0
23249	2021-10-10 19:22:13.113	info	Pierre - Connected client

chromecast.0
23249	2021-10-10 19:22:13.107	info	Wohnzimmer - Connected client

chromecast.0
23249	2021-10-10 19:22:13.100	info	Andrew - Connected client

chromecast.0
23249	2021-10-10 19:22:13.040	info	State value to set for "chromecast.0.Google_home_pierre.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:13.037	info	State value to set for "chromecast.0.Tedt.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.989	info	State value to set for "chromecast.0.Tv_Eltern.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.986	info	State value to set for "chromecast.0.Google_Home_PC_Raum.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.983	info	State value to set for "chromecast.0.Wohnzimmer.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.981	info	State value to set for "chromecast.0.Pierre.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.978	info	State value to set for "chromecast.0.Andrew.port" has to be type "string" but received type "number"

chromecast.0
23249	2021-10-10 19:22:12.368	info	starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.chromecast, node: v12.22.6, js-controller: 3.3.18

chromecast.0
22807	2021-10-10 19:21:39.851	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

chromecast.0
22807	2021-10-10 19:21:39.850	info	terminating

chromecast.0
22807	2021-10-10 19:21:39.850	info	Unload completed sucesfully

chromecast.0
22807	2021-10-10 19:21:39.849	info	Tedt - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.849	info	Tv Eltern - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.848	info	Tv Eltern - Detached player

chromecast.0
22807	2021-10-10 19:21:39.847	info	Tv Eltern - Detached player

chromecast.0
22807	2021-10-10 19:21:39.846	info	Google Home PC Raum - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.845	info	Google home pierre - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.844	info	Pierre - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.843	info	Pierre - Detached player

chromecast.0
22807	2021-10-10 19:21:39.842	info	Pierre - Detached player

chromecast.0
22807	2021-10-10 19:21:39.841	info	Wohnzimmer - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.840	info	Wohnzimmer - Detached player

chromecast.0
22807	2021-10-10 19:21:39.839	info	Wohnzimmer - Detached player

chromecast.0
22807	2021-10-10 19:21:39.837	info	Andrew - client disconnected

chromecast.0
22807	2021-10-10 19:21:39.834	info	Destroying chromecast scanner

chromecast.0
22807	2021-10-10 19:21:39.833	info	Unload triggered

chromecast.0
22807	2021-10-10 19:21:39.821	error	Cannot read property 'contentId' of undefined

chromecast.0
22807	2021-10-10 19:21:39.820	error	TypeError: Cannot read property 'contentId' of undefined at PersistentPlayer._playerStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58) at DefaultMediaReceiver.emit (events.js:314:20) at fn.onstatus (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10) at fn.emit (events.js:314:20) at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12) at fn.emit (events.js:326:22) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:314:20) at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10) at Client.emit (events.js:326:22)

chromecast.0
22807	2021-10-10 19:21:39.819	error	uncaught exception: Cannot read property 'contentId' of undefined

chromecast.0
22807	2021-10-10 19:21:39.740	info	Tv Eltern - Player joint

chromecast.0
22807	2021-10-10 19:21:39.738	info	Tv Eltern - Connected player

chromecast.0
22807	2021-10-10 19:21:39.735	info	Tv Eltern - Try to join player

chromecast.0
22807	2021-10-10 19:21:39.718	info	State value to set for "chromecast.0.Google_home_pierre.player.shuffleMode" has to b
```

**Comment by focus1610** [comment]
Ich habe das gleiche Problem. Ich meine das es kam als ich einen Android TV bekommen habe.
Es hilft nichts. Adapter deinstallieren und neu installieren. Die ganzen Objektbäume einmal löschen. Nichts hilft.
Ist der Entwickler noch aktiv?

**Comment by michipi85** [comment]
@focus1610 versuch mal die v3.0.0 die funktioniert bei mir soweit wieder.

**Comment by funky4t** [comment]
@michipi85 
> @focus1610 versuch mal die v3.0.0 die funktioniert bei mir soweit wieder.

Ich hab das repository soeben auf latest umgestellt, kann dann auch gezielt die V3.0.0 auswählen, aber während des Installationsvorgangs bekomme ich die Info, dass die Version nicht verfügbar sei.... am Ende bleibe ich auf V2.3.1 ....sehr strange... Gibt es noch einen anderen Weg an die 3.0.0 zu gelangen?

<img width="715" alt="Bildschirmfoto 2021-11-29 um 09 46 41" src="https://user-images.githubusercontent.com/57875762/143835770-0edf0572-ebc2-47f8-affe-06c189c461f7.png">

**Comment by michipi85** [comment]
@funky4t du kannst es über den Expertenmodus updaten. Expertenmodus aktiviern, über die Katze auf "von Github" springen und dort chromecast auswählen und updaten.

Oder über die shell

`iobroker update
iobroker upgrade chromecast@3.0.0
`

**Comment by funky4t** [comment]
@michipi85 
> @funky4t du kannst es über den Expertenmodus updaten. Expertenmodus aktiviern, über die Katze auf "von Github" springen und dort chromecast auswählen und updaten.
> 
> Oder über die shell
> 
> `
> 
> > 1. iobroker update
> > 2. iobroker upgrade chromecast@3.0.0
> >    `

Habs mal üb er die Shell probiert, leider auch nicht:
<img width="488" alt="Bildschirmfoto 2021-11-29 um 10 29 27" src="https://user-images.githubusercontent.com/57875762/143842934-7eb995a8-8d0a-4c36-ab7b-1da911c7b298.png">

**Comment by funky4t** [comment]
über Github klappt der Install von 3.0.0, leider meldet der Adapter dann das der "net-Tool" Adapter fehlt.....

<img width="986" alt="Bildschirmfoto 2021-12-04 um 16 10 43" src="https://user-images.githubusercontent.com/57875762/144714592-d6670099-912d-41b1-bd2f-7af35bbaa209.png">

Der "net-Tool" ist aber installiert und hat auch eine ganze Reihe Devices entdeckt. Allerdings erschließt sich mir nicht ganz, ob/wie ich die beiden konfigurieren muss, damit chromecast meinen Mini im Netz entdeckt und wieder im Instanzenbaum aufführt.... Bei den Objects ist bei Chromecast außer Admin nämlich nichts zu finden. 

Beim Net-Tools schaut es so aus:
<img width="1149" alt="Bildschirmfoto 2021-12-04 um 16 14 03" src="https://user-images.githubusercontent.com/57875762/144714751-0cbec5c4-386f-4f0b-9c7f-00955cb03a83.png">

Restarts vom Chromcast Adapter bringen immer wieder die obige Fehlermeldung im Log aber keine DPs im Chromecast Adapter. Auch das manuelle Anlegen eines Devices im Chromecast bringt keine Abhilfe....

Kann mir bitte wer helfen, wie ich den Baum umschubse, der mir die Sicht auf den Wald versperrt? Ich sag schonmal herzlichen Dank im Voraus

**Comment by Jey-Cee** [comment]
@funky4t hast du ein Multihost system?

**Comment by funky4t** [comment]
> @funky4t hast du ein Multihost system?

Nein, Standalone auf Raspberry Pi4.

**Comment by Jey-Cee** [comment]
Alles was mit der V3 zu tun hat bitte hier Diskutieren: https://forum.iobroker.net/post/716020

**Comment by Jey-Cee** [comment]
Same as #95

**Comment by olli0815** [comment]
Die 3.0 aus dem GIT lässt sich bei mir nicht installieren, der Fehler der (bei mir) in der 2.3.1 zum crash führt, lässt sich gut reproduzieren:

sobald ich den Google TV stick ins gleiche Netz hänge & etwas abspiele, raucht der Adapter ab, weil er den Payer nicht vernünftig auslesen kann:

<html><body>


chromecast.1 | 2022-01-01 17:15:32.323 | error | Cannot read property 'contentId' of undefined
-- | -- | -- | --
chromecast.1 | 2022-01-01 17:15:32.321 | error | TypeError:  Cannot read property 'contentId' of undefined    at  PersistentPlayer._playerStatus  (/opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:719:58)     at DefaultMediaReceiver.emit (events.js:314:20)    at fn.onstatus  (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:16:10)     at fn.emit (events.js:314:20)    at fn.onmessage  (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:21:12)     at fn.emit (events.js:314:20)    at Channel.onmessage  (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10)     at Channel.emit (events.js:314:20)    at Client.onmessage  (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10)    at  Client.emit (events.js:326:22)
chromecast.1 | 2022-01-01 17:15:32.315 | error | uncaught exception: Cannot read property 'contentId' of undefined


</body>
</html>

**Comment by Jey-Cee** [comment]
Please test v3.0.1. But be aware this version has breaking changes.
You also need to install net-tools by hand as this will not be installed automatically.

**Comment by funky4t** [comment]
Version 3.0.1 founds net-Tools on my system, so no longer log entries "no installed net-tools". Bad thing is it still crashes again after some minutes on my system. IOBroker still reports to many restarts and deactivates the instance automatically

**Comment by Jey-Cee** [comment]
What says the log about the crash?

**Comment by funky4t** [comment]
Here the log:

<img width="1278" alt="Bildschirmfoto 2022-01-16 um 10 35 27" src="https://user-images.githubusercontent.com/57875762/149654673-be11c3b2-3f85-4a8b-85e0-5cfdceebc734.png">

**Comment by olli0815** [comment]
> Please test v3.0.1. But be aware this version has breaking changes. You also need to install net-tools by hand as this will not be installed automatically.

no, even with running net-tools, I can't get it to work, from 3.x. on.

**Comment by Jey-Cee** [comment]
@funky4t Bitte mal in den Ordner

`/opt/iobroker/node_modules/iobroker.chromecast`
gehen und folgenden Befehl ausführen:

`npm update castv2-player`

**Comment by funky4t** [comment]
> @funky4t Bitte mal in den Ordner
> 
> `/opt/iobroker/node_modules/iobroker.chromecast` gehen und folgenden Befehl ausführen:
> 
> `npm update castv2-player`


Seit einer knappen Stunde ohne Absturz! Sieht gut aus bei mir! Besten Dank... 👌🏼
