### ISSUE TITLE
Playing a YTMusic song via Chromecast not working

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.chromecast#101]
Hello,

What are the possibilities to launch a song from YouTube Music via API on Google Home?

I play YTMusic with Google Home. 
When I read the Google Home Api, the media.contentID is ExvqA9I_gsQ for example. This is the ID of the song that is playing. 
Now I want to send a trigger via API that will continue playing the song after a previously triggered pause. 
Normally you enter a URL in the player.url2play attribute. 
The corresponding URL of YTMusic which works in the browser would be https://music.youtube.com/watch?v=ExvqA9I_gsQ.
However, Google Home does not recognize the URL of YTMusic and does not play the song. Also the media.contentID in the url2play field alone does not work.

What are the possibilities to start a song from YouTube Music via API on Google Home?

Spotify offers an extra API backend for this, which you can use to create a premium login URL if the missing login on the YT URL would be the problem. Do YT have something like this?

Regards

**Comment by maxpd1** [comment]
I assume the Authorization Header of YTM has to be implemented so that the played songs know the account from which they have to be played. Is there a possbility to add this into the adapter or solve this via a JS-Script?

**Comment by maxpd1** [comment]
Thanks, but seems as there isn't any chromecast adapter developer anymore. Even if there was a slight version change some weeks ago.

**Comment by raintonr** [comment]
YTM app ID: 4Fm7OudrAYE

Maybe this can be done in the same way as #75

**Comment by maxpd1** [comment]
Would be great but needs knowhow of a developer. My monthly reminders to YTM to setup a small API to at least start/stop a playlist doesn't seem to have any effect :D
