### ISSUE TITLE
[Bug]: Crash-Loop beim Abspielen von Amazon Video

### ISSUE THREAD

**Issue by AndreS235** [iobroker-community-adapters/ioBroker.chromecast#104]
### Contact Details

gith@andreschmidt.de

### What happened?

Wenn man auf einem Chromecast Amazon-Prime-Video abspielt crasht der Adapter immer wieder bis er wegen Crash-Loop nicht mehr gestartet wird. Sowohl Version 2.3.1 als auch 3.0. Es gibt keine Probleme mit Netflix, Youtube, YT-Music und Kodi.

### Adapter Version

2.3.1 und 3.0

### JS-Controller Version

latest

### Node JS Version

latest

### NPM Version

latest

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Please test v3.0.1. But be aware this version has breaking changes.
You also need to install net-tools by hand as this will not be installed automatically.

**Comment by Hagbard235** [comment]
v3.0.1 seems to work until now
