### ISSUE TITLE
Please report this to the developer. 

### ISSUE THREAD

**Issue by Brainbug01** [iobroker-community-adapters/ioBroker.chromecast#115]
Node.js:v12.22.10
NPM:v6.14.16
JS: 4.0.19

```
chromecast.0 | 2022-03-06 09:41:15.938 | warn | This object will not be created in future versions. Please report this to the developer.
chromecast.0 | 2022-03-06 09:41:15.937 | warn | Object chromecast.0.B.player.shuffleMode is invalid: Default value has to be type "boolean" but received type "string"
chromecast.0 | 2022-03-06 09:41:15.937 | warn | This object will not be created in future versions. Please report this to the developer.
chromecast.0 | 2022-03-06 09:41:15.937 | warn | Object chromecast.0.B.player.repeatMode is invalid: Default value has to be type "number" but received type "string"
chromecast.0 | 2022-03-06 09:41:15.937 | warn | This object will not be created in future versions. Please report this to the developer.
chromecast.0 | 2022-03-06 09:41:15.936 | warn | Object chromecast.0.B.playlist.currentItemId is invalid: Default value has to be type "number" but received type "object"
chromecast.0 | 2022-03-06 09:41:15.936 | warn | This object will not be created in future versions. Please report this to the developer.
chromecast.0 | 2022-03-06 09:41:15.936 | warn | Object chromecast.0.B.playlist.list is invalid: Default value has to be stringified but received type "object"
chromecast.0 | 2022-03-06 09:41:15.935 | warn | This object will not be created in future versions. Please report this to the developer.
chromecast.0 | 2022-03-06 09:41:15.935 | warn | Object chromecast.0.B.player.state is invalid: Default value has to be type "number" but received type "string"
```

**Comment by Berchemer** [comment]
Same here...
Adapter is v3.0.1 from Github.
Re-Installed 08.08.2022

```
2022-03-08 16:04:01.943  - info:  chromecast.0 (114438) State value to set for  "chromecast.0.A.playlist.list" has to be stringified but  received type "object"
2022-03-08 16:04:01.943  - info:  chromecast.0 (114438) State value to set for  "chromecast.0.A.player.repeatMode" has to be type "number"  but received type "string"
2022-03-08 16:04:01.943  - info:  chromecast.0 (114438) State value to set for  "chromecast.0.A.player.shuffleMode" has to be type "boolean"  but received type "string"

```

**Comment by Berchemer** [comment]
Maybe I should also add this info after a complete new install of the chromecast adapter v3.0.1:

`chromecast.0 2022-03-09 09:47:57.642	warn	State "chromecast.0.XXSerialNumberXX.status.connected" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.576	warn	State "chromecast.0.XXSerialNumberXX.player.currentTime" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.575	warn	State "chromecast.0.XXSerialNumberXX.player.state" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.351	warn	State "chromecast.0.XXSerialNumberXX.player.url2play" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.350	warn	State "chromecast.0.XXSerialNumberXX.enabled" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.199	warn	State "chromecast.0.XXSerialNumberXX.status.playing" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.197	warn	State "chromecast.0.XXSerialNumberXX.status.connected" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.196	warn	State "chromecast.0.XXSerialNumberXX.port" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.195	warn	State "chromecast.0.XXSerialNumberXX.address" has no existing object, this might lead to an error in future versions
chromecast.0 2022-03-09 09:47:57.128	warn	Object chromecast.0.XXSerialNumberXX.player.shuffleMode is invalid: Default value has to be type "boolean" but received type "string"
chromecast.0 2022-03-09 09:47:57.127	warn	This object will not be created in future versions. Please report this to the developer.
chromecast.0 2022-03-09 09:47:57.127	warn	Object chromecast.0.XXSerialNumberXX.player.repeatMode is invalid: Default value has to be type "number" but received type "string"
chromecast.0 2022-03-09 09:47:57.126	warn	This object will not be created in future versions. Please report this to the developer.
chromecast.0 2022-03-09 09:47:57.125	warn	Object chromecast.0.XXSerialNumberXX.playlist.currentItemId is invalid: Default value has to be type "number" but received type "object"
chromecast.0 2022-03-09 09:47:57.125	warn	This object will not be created in future versions. Please report this to the developer.
chromecast.0 2022-03-09 09:47:57.124	warn	Object chromecast.0.XXSerialNumberXX.playlist.list is invalid: Default value has to be stringified but received type "object"
chromecast.0 2022-03-09 09:47:57.123	warn	This object will not be created in future versions. Please report this to the developer.
chromecast.0 2022-03-09 09:47:57.123	warn	Object chromecast.0.XXSerialNumberXX.player.state is invalid: Default value has to be type "number" but received type "string"
chromecast.0 2022-03-09 09:47:57.121	warn	This object will not be created in future versions. Please report this to the developer.`

**Comment by aortmannm** [comment]
Yeah same for me :/
