### ISSUE TITLE
[Bug]: Default media player suddenly stopped working on Chromecast devices

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.chromecast#120]
### What happened?

I noticed a few hours ago that for some reason playing sounds (we have some notification sounds and announcements via SayIt) just stopped working. This was to a Chromecast Mini. I have tried sending sounds to a regular Chromecast and that seems broken too.

Nothing in the log. Says it's playing but nothing actually comes out of the speaker.

Tried reboot, etc. but nothing seems to work.

### Adapter Version

3.0.1

### JS-Controller Version

4.0.23

### Node JS Version

v12.22.5

### NPM Version

7.5.2

### Operating System

Debian

**Comment by Apollon77** [comment]
Any more insights?

**Comment by petterpet** [comment]
I noticed too that the default media doesn't work anymore. When I try to play a webradio playlist I get the following errors:
1. `NestHub - Cannot play file "http://www.rockantenne.de/webradio/rockantenne.m3u": TypeError: Cannot use 'in' operator to search for 'content-type' in undefined`
2. `NestHub - Error playing playlist - TypeError: Cannot use 'in' operator to search for 'content-type' in undefined at MediaInfo._parseIcyHeaderPromise (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:143:26) at /opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:47:43 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 0) at async Promise.all (index 1)`

"NestHub" is the name of my chromecast-device.

---
Adapter-Version: 2.3.1
JS-Controller: 4.0.23
NodeJS: 16.16.0
OS: Ubuntu

**Comment by Apollon77** [comment]
@petterpet What has this to do with the issue you commented on? 
Additionally: Please try the Beta version 3.0.3 ... your issue is already fixed there

**Comment by petterpet** [comment]
I commented on this issue because it describes my problem well.
Thanks, I will try it.

**Comment by Apollon77** [comment]
PS: Hm ... but with the difference that you have a crash in your log, this use has nothing - nd also did not reponded to any more detail questions... so close for now. Can be reopened or create new issue with more details

**Comment by petterpet** [comment]
> I noticed too that the default media doesn't work anymore. When I try to play a webradio playlist I get the following errors:
> 
> 1. `NestHub - Cannot play file "http://www.rockantenne.de/webradio/rockantenne.m3u": TypeError: Cannot use 'in' operator to search for 'content-type' in undefined`
> 2. `NestHub - Error playing playlist - TypeError: Cannot use 'in' operator to search for 'content-type' in undefined at MediaInfo._parseIcyHeaderPromise (/opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:143:26) at /opt/iobroker/node_modules/castv2-player/lib/mediaInfo.js:47:43 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Promise.all (index 0) at async Promise.all (index 1)`
> 
> "NestHub" is the name of my chromecast-device.
> 
> Adapter-Version: 2.3.1 JS-Controller: 4.0.23 NodeJS: 16.16.0 OS: Ubuntu

Fixed in V3.0.3
