### ISSUE TITLE
[Bug]: Object trees not created for all discovered devices +  '(incomplete)' tree

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.chromecast#121]
### What happened?

We have several chromecast devices here, but on startup objects are only correctly create for one of them.

This didn't used to be the case - the adapter has been working well for us in the past. I discovered this while trying to debug #120. I stopped the adapter, deleted the object tree and restarted which reproduces this fault.

Looking in the logs I see that all devices are correctly discovered. There then follows 'Connected client' messages and 'Update client status' messages. I imagine that somewhere in this startup the objects for each device discovered should be created but that doesn't happen.

This ends up creating a tree for '(incomplete)' and one other device only (which happens to be a Sony Android TV but not sure that is relevant). So of the 5 devices discovered, only one (the TV) has it's object tree correctly created.

We also have 2 speaker groups for which object trees do seem to be correctly created (although there are many warnings about types in the log).

### Adapter Version

3.0.1

### JS-Controller Version

4.0.23

### Node JS Version

v12.22.5

### NPM Version

7.5.2

### Operating System

Debian

**Comment by Apollon77** [comment]
Were you able to debug further and find a solution?
