### ISSUE TITLE
[Bug]: "net-tools" not found

### ISSUE THREAD

**Issue by data2000** [iobroker-community-adapters/ioBroker.chromecast#132]
### What happened?

Bei der Installation von V3.0.3 erhalte ich diese Ausgabe

$ ./iobroker upgrade chromecast
ERROR: Cannot check dependencies: Required dependency "net-tools" not found.
process exited with code 0

Der Versuch einer Neuinstallation der net-tools bringt als Ergebnis
net-tools is already the newest version (1.60+git20180626.aebd88e-1).

Die Suche per google brachte mich hier leider auch nicht weiter.

### Adapter Version

3.0.3

### JS-Controller Version

4.0.23

### Node JS Version

16.17.0

### NPM Version

6.14.10

### Operating System

Debian

**Comment by Fiiti** [comment]
+1
