### ISSUE TITLE
Github test & release workflow is broken

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.chromecast#140]
### What happened?

Automated tests report...

```
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
```

... and I note @GermanBluefox recently added `package-lock.json` to `.gitignore` so, erm, why? Do we not care about these tests any more or are there plans to clean this up?

### Adapter Version

N/A

### JS-Controller Version

N/A

### Node JS Version

N/A

### NPM Version

N/A

### Operating System

Ubuntu

**Comment by mcm1957** [comment]
fixed
