### ISSUE TITLE
[Bug]: Webserver settings not properly saved/derived if chosen web instance bound to single interface

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.chromecast#145]
### Contact Details

robin@rainton.com

### What happened?

This Chromecast adapter has 1 or 2 drop configuration down values regarding web instances:

1. _Web instance_ : Mandatory. This is the actual instance number (eg. `web.0`, `web.1`, etc).
2. _Web server IP_ : Optional. This is only shown if the chosen web instance is bound to all interfaces.

I recently re-configured our IoB web instances to only listen on a single interface (good security practice).

What this means is that the _Web server IP_ configuration option disappears and a null value is stored for `adapter.config.webServer` setting.

As a result, trying to play local files (by setting the appropriate state) causes the error messages, _'Sorry, cannot play file'_, _'Please configure webserver settings first!'_ to be logged.

### Adapter Version

3.1.0

### JS-Controller Version

4.0.23

### Node JS Version

v16.17.1

### NPM Version

8.15.0

### Operating System

Debian

### Relevant log output

```shell
2022-12-24 19:29:41.066  - error: chromecast.0 (8597) Nest_Mini- Sorry, cannot play file "/some/file/here.mp3"
2022-12-24 19:29:41.067  - error: chromecast.0 (8597) Nest_Mini- Please configure webserver settings first!
```
```


### Anything else?

_No response_

**Comment by raintonr** [comment]
As an FYI, a workaround is:

1. Configure the required web instance to listen on all interfaces.
2. Configure the Chromecast adapter to use the required web instance. As the web instance is not using a single interface, the _Web server IP_ option will be shown and the required address can be chosen.
3. Return to the web instance configuration and change to only listen on the required interface.

While this works, it shows a rather nasty problem that occurs when one adapter is reliant on another. There should be a more defined API/interface in place for configuration of such dependencies.

**Comment by raintonr** [comment]
@GermanBluefox ... I will fix this after #103 is merged.

**Comment by divY42** [comment]
you just closed my ticket and marked it as a duplicate, but your workaround for me is not working because:

> 2\. Configure the Chromecast adapter to use the required web instance. As the web instance is not using a single interface, the _Web server IP_ option will be shown and the required address can be chosen.

My issue is I actually cannot change my adress

**Comment by raintonr** [comment]
For the record, this mechanism is rather clumsy because if one re-configures their web adapter interface settings it may mean that any Chromecast adapter using that will stop working until it too is re-configured.

A slightly nicer way might be to remove the IP address option from the Chromecast adapter and have it work out the address to use by looking at web adapater and Chromecast device subnets (or some other logic?).
