### ISSUE TITLE
Resume played media after Sayit text is played

### ISSUE THREAD

**Issue by smalltower1** [iobroker-community-adapters/ioBroker.chromecast#155]
When casting music from Spotify on Google Home speakers and Sayit plays a text over the same speakers, the Spotify streaming is stopped and not resumed once the text has been played. 
Request: If Chromecast is streaming content and a Sayit text is received, the steamed content is paused and after the Sayit text has been played it resumes.
Any chance this function could be implemented?

**Comment by raintonr** [comment]
Valid point, but in order to achieve this one would have to know not only what track was playing, but how that track came to be playing (part of a playlist, infinite play, etc, etc). For all the streaming services available I think this would be very hard to implement.
