### ISSUE TITLE
[Bug]: uncaught exception: Cannot use 'in' operator to search for 'displayName' in undefined

### ISSUE THREAD

**Issue by transwarp604** [iobroker-community-adapters/ioBroker.chromecast#156]
### What happened?

Hi Team,
My Adapter is crashing and unload will be triggered With 

1. uncaught exception: Cannot use 'in' operator to search for 'displayName' in undefined
2. TypeError: Cannot use 'in' operator to search for 'displayName' in undefined at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:639:41) at MediaPlayer.emit (events.js:400:28) at PersistentClient.emit (events.js:412:35) at PersistentClient._updateStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentClient.js:334:12) at /opt/iobroker/node_modules/castv2-player/lib/persistentClient.js:262:20 at /opt/iobroker/node_modules/castv2-client/lib/controllers/receiver.js:31:5 at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/request-response.js:27:7) at fn.emit (events.js:412:35) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:400:28)
3. Cannot use 'in' operator to search for 'displayName' in undefined
4. unload will be triggred

Help would be Great! If more infos needed, just request.

### Adapter Version

2.3.1

### JS-Controller Version

4.0.24

### Node JS Version

14.21.2

### NPM Version

6.14.17

### Operating System

Debian

### Relevant log output

```shell
Cannot use 'in' operator to search for 'displayName' in undefined at ChromecastDevice._updateClientStatus (/opt/iobroker/node_modules/iobroker.chromecast/lib/chromecastDevice.js:639:41) at MediaPlayer.emit (events.js:400:28) at PersistentClient.emit (events.js:412:35) at PersistentClient._updateStatus (/opt/iobroker/node_modules/castv2-player/lib/persistentClient.js:334:12) at /opt/iobroker/node_modules/castv2-player/lib/persistentClient.js:262:20 at /opt/iobroker/node_modules/castv2-client/lib/controllers/receiver.js:31:5 at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/request-response.js:27:7) at fn.emit (events.js:412:35) at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10) at Channel.emit (events.js:400:28)
```

**Comment by raintonr** [comment]
2.3.1 is quite an old version. Could you please try 3.0.3? Although note this is a breaking change as the channel names will change.

**Comment by transwarp604** [comment]
Good and valid point, my repo setup was not accurate. Update was helpful! Thanks for the support!
