### ISSUE TITLE
[Bug]: .status.volume is missing after Update to 3.x

### ISSUE THREAD

**Issue by RicoAeckerle** [iobroker-community-adapters/ioBroker.chromecast#157]
### Contact Details

rico.aeckerle@gmail.com

### What happened?

After Update to 3.x the object Status.Volume is missing.

### Adapter Version

3.0.3

### JS-Controller Version

4.0.24

### Node JS Version

v16.19.0

### NPM Version

8.19.3

### Operating System

Debian

**Comment by raintonr** [comment]
Please use `...player.volume`
