### ISSUE TITLE
How to play video and audio simultaneously

### ISSUE THREAD

**Issue by piDNS** [iobroker-community-adapters/ioBroker.chromecast#203]
First I want to thank you, because I like to use your Adapter.
I use it to play YouTube Videos in 720p30 directly without advertisements (url2play).

If I want to have a higher video quality, YouTube splits up the media. E.g. there is a webm 1080p60 video and a webm 160k audio file like seen in this table:

https://gist.github.com/sidneys/7095afe4da4ae58694d128b1034e01e2

So I ask you to help me playing a video and an audio file on the chromecast simultaneously. Somehow it has to be possible, because the YouTube app does it similar while streaming.

A big thank you to all of you!

_examples:_

**mp4 720p30 video and audio**
https://[rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737615&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=22&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=313.840&lmt=1673623722382325&mt=1696715341&fvip=3&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgb6eGDgHKvAwH5q5zo_3WSdLNfn_ePTO0iK0OsRumMrsCIQDe0DcThu54eC1cJOo_L7ExfyqevDEnJnOzr8ubmrIfYQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com](https://rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737615&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=22&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=313.840&lmt=1673623722382325&mt=1696715341&fvip=3&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AGM4YrMwRQIgb6eGDgHKvAwH5q5zo_3WSdLNfn_ePTO0iK0OsRumMrsCIQDe0DcThu54eC1cJOo_L7ExfyqevDEnJnOzr8ubmrIfYQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com) 

**webm 1080p60 video**
https://[rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737614&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=303&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=134710778&dur=313.780&lmt=1647456864300547&mt=1696715341&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAK63pPmQzr6BtLONbh6tCFwrTKmg_M0cZ7FMAPSsuyvsAiBIZ0RmXXmURtoOepVomcc2LYNWHBvDNbuT4DtblqP6MQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com](https://rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737614&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=303&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=134710778&dur=313.780&lmt=1647456864300547&mt=1696715341&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAK63pPmQzr6BtLONbh6tCFwrTKmg_M0cZ7FMAPSsuyvsAiBIZ0RmXXmURtoOepVomcc2LYNWHBvDNbuT4DtblqP6MQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com)

**webm 160k audio**
https://[rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737614&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=251&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=5199784&dur=313.801&lmt=1647453650291076&mt=1696715341&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRgIhALG_74hWePLS6Efed99toEXpKDA1AbQxyJpz7vtkttDsAiEAyTuaHIuhotGat-PFvHjBO7A1GYXBe1X-cTzkgKG3jiw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com](https://rr3---sn-4g5edndz.googlevideo.com/videoplayback?expire=1696737614&ei=7tQhZYveO92v6dsP-9ex-AY&ip=84.63.233.45&id=o-ABBsrpOTc_6xVOtYL00bnQcmY5lTR4AY9Qb8hWS4GT8s&itag=251&source=youtube&requiressl=yes&mh=NH&mm=31%2C26&mn=sn-4g5edndz%2Csn-5hneknee&ms=au%2Conr&mv=m&mvi=3&pl=20&initcwndbps=1406250&spc=UWF9f-zVQG65bc66VPV_BdR9GbJFTEk&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=5199784&dur=313.801&lmt=1647453650291076&mt=1696715341&fvip=3&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRgIhALG_74hWePLS6Efed99toEXpKDA1AbQxyJpz7vtkttDsAiEAyTuaHIuhotGat-PFvHjBO7A1GYXBe1X-cTzkgKG3jiw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRAIgKPm97JN2pCm4KcSZuaPLj3eUg5W7pmLRSD2gEeRLICICIBzQHUPqwoM-375Dlb_w3N9FI0y5KLSFLG_mG5sJgVSs&host=rr3---sn-4g5edndz.googlevideo.com)

**Comment by raintonr** [comment]
In a word: No. Beyond the scope of this adapter.

However, if you want to combine video and audio streams then maybe look at FFmpeg. I imagine there is a way to tell it to do what you want. Ie. take this video stream + that audio stream and serve up a output stream with them synchronised and combined. You can then send that combined stream that to any device you like, right?
