### ISSUE TITLE
wrong data in ...metadata.title field

### ISSUE THREAD

**Issue by etv99** [iobroker-community-adapters/ioBroker.chromecast#26]
Since the rewrite to 1.2.x the field contains always the station name when playing webradio instead of the real title of the song.....

thanks
tom

**Comment by angelnu** [comment]
From what I can tell reviewing the code the title should be detected as before... So I would need to check the ICY data from the radio stream you are using.

Could you please provide the URL of the webradio you are testing?

**Comment by etv99** [comment]
Good Morning,

it's on all stations we hear - and was OK with all stations until version
1.2.

Here are all stations:
- http://live.antenne.at/as
- http://soft.lolliradio.net:8040/stream
- http://94.23.66.155:8030/;stream.nsv
- http://mp3channels.webradio.antenne.de/chillout
- http://mp3stream7.apasf.apa.at/;stream.nsv


Thanks
tom

Am 29.01.2018 23:47 schrieb "Vegetto" <notifications@github.com>:

**Comment by angelnu** [comment]
I can confirm that I get the original metadata header but afterwards we should be getting aditional metadata for the title. This will require more investigation...

This the code to intercept the title metadata in the cast2-player node.js module:
```
// log any "metadata" events that happen                                                                       
        res.on('metadata', that._gotMetadata.bind(that, res));
```

And this the metadata header:
```
{ 'content-type': 'audio/mpeg',
--
date: 'Tue, 30 Jan 2018 22:17:38 GMT',
'icy-br': '128, 128',
'ice-audio-info': 'ice-samplerate=44100;ice-bitrate=128;ice-channels=2',
'icy-description': 'Immer einen Hit voraus',
'icy-genre': 'Top40',
'icy-name': 'Antenne Steiermark',
'icy-pub': '1',
'icy-url': 'http://www.antenne.at',
server: 'Icecast 2.4.0-kh7',
'cache-control': 'no-cache, no-store',
'access-control-allow-origin': '*',
'access-control-allow-headers': 'Origin, Accept, X-Requested-With, Content-Type',
'access-control-allow-methods': 'GET, OPTIONS, HEAD',
connection: 'Close',
expires: 'Mon, 26 Jul 1997 05:00:00 GMT',
'icy-metaint': '16000' }


```

**Comment by etv99** [comment]
Hi,

OK, I will try to look for this Part of Code also in the old version....

Thanks
Tom

Am 30.01.2018 23:58 schrieb "Vegetto" <notifications@github.com>:

**Comment by angelnu** [comment]
@etv99 - did you try with the old version?

**Comment by Jey-Cee** [comment]
Seems this works in version 2.3.1. So i close this issue.
