### ISSUE TITLE
Sorry, update for [DEVICE].player.url2play not supported!

### ISSUE THREAD

**Issue by esusxunil** [iobroker-community-adapters/ioBroker.chromecast#273]
### Contact Details

sebastian.schnack@gmail.com

### What happened?

Hello, 

I updated to the latest Version 3.4.0 of the Adapter.

In general everything is working well, but I get following error message after each update of a data point :

`Sorry, update for [DATAPOINT] not supported!`

Funny is that it still works - just the error messages spam the log.

### Adapter Version

3.4.0

### JS-Controller Version

5.0.19

### Node JS Version

18.20.2

### NPM Version

10.7.0

### Operating System

Debian

### Relevant log output

```shell
chromecast.0
2024-05-15 16:11:36.793	error	Büro - Sorry, update for Nest_Mini.player.url2play not supported!

chromecast.0
2024-05-15 16:11:33.082	error	Büro - Sorry, update for Nest_Mini.player.volume not supported!

chromecast.0
2024-05-15 16:11:24.395	error	Büro - Sorry, update for Nest_Mini.player.url2play not supported!

chromecast.0
2024-05-15 16:10:49.905	error	Büro - Sorry, update for Nest_Mini.player.announcement not supported!
```

**Comment by neopholus** [comment]
Hi Sebastian,

How do you update the data points?
Manually? Javascript? Blockly?
Can you please provide a screenshot?

BR, Stefan

**Comment by esusxunil** [comment]
Hi Stefan,

I use another Adadpter, the sayit adapter. Is that something the other adapter need to change, for example use other Databpoints?

**Comment by neopholus** [comment]
I also use sayit and it works well. The only difference I see is that I use Google Mini and you use Nest devices. Can you delete the chromecast data points in the Objects tab and them restart the chromecast adapter?

If that does not help, please post a screenshot of your sayit configuration.

**Comment by esusxunil** [comment]
I use two Say It instances, one for a Chromecast Audio - this works well - and another one for the Nest Mini - this plays the announcements, too, but throw error massages.

While creating the Screenhot, I saw I can select Type "Google Home" instead of Chromecast - I will give it a try.

![image](https://github.com/user-attachments/assets/d10d991d-6ff2-4d4e-9ad7-6a72718a3827)

**Comment by esusxunil** [comment]
One update: with Type "Google Home" and manually entering the IP in the SayIt Instance it works as well and does not throw the error anymore. For me it is a valid workaround.

Only open question - for me less important: Why does the Chromecast adapter has issues with (some) devices. I tested it with all my devices with Chromecast Support

Devices that worked without Errormessage:
- Google Chromecast Audio
- Nvidia TV Shield Pro

Devices that worked but with Errormessage:
- Google Nest Mini
- Google Nest Hub
- Google TV

**Comment by raintonr** [comment]
I noticed with controller 6.x `url2play` stopped working, so updated chromecast adapter to 4.0 but that did not fix the issue.

Strangely my sayit instance works just fine, but trying to play media files from the IoB host (via webserver of course) does not work.

**Comment by raintonr** [comment]
I notice sayit sets `${chromecastDevice}.player.announcement` and not `${chromecastDevice}.player.url2play`

**Comment by raintonr** [comment]
I'm going to close this because updating `url2play` in the latest version works just fine... *for real URLS*. It does not work for local files but that is another matter.

**Comment by mcm1957** [comment]
> I'm going to close this because updating `url2play` in the latest version works just fine... _for real URLS_. It does not work for local files but that is another matter.

Please add an more detailled error description of "does not work for local files" and attach a log if available.

**Comment by raintonr** [comment]
See #323
