### ISSUE TITLE
Play again last played stream does not work

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.chromecast#29]
The documentation says 
"Play again last played stream: just set chromecast.0.<your device>.status.playing to true".

1. Command does not work. When setting "playing" to true, the speaker stays silent after an annoucement.
2. The role of correponding object "playing" is set to status and not to command.

Tested on Adapter Version: 1.4.1

**Comment by angelnu** [comment]
When you set playing to true the resukt is that the value of url2play will be played. If the last thing was an announcement then the save announcement will be played again. For announcements the asked should resume automatically assuming it has being playing before something that can be resumed: if you were streaming from an all such as Spotify it dies not work.

I am not sure I understand what you mean by playing bring set to status... When you set playing to true it will get acknowledged if it was able to play. If this did not work out will tending true but without acknowledge. The problem will be displayed in the log.

**Comment by Marty56** [comment]
What I meant with "playing is set to status": If I am looking at the column "role" in the objects tab of the administrator it says "status". This normal indicates that this object im meant for reading and not for writing thus becoming a "command". Maybe this is just a matter of wrong documentation and not really an issue. Since there is practically no documentation I am always looking at the column to find out whether it may have effect and normally "status" cannot be used as a command.

What would be desired is that if user is  e.g. streaming a radio, playing a music file or whatever, this media should resume after the announcement. 

One additional question: When should "playing" be set to "true" before the announcement or after?

**Comment by angelnu** [comment]
The object status.playing is defines as writable to reflect that you can write it from ioBroker. So it is an status and command in one. I implemented this way so I can use simple vis widgets to show and set the status of the chromecast:

![image](https://user-images.githubusercontent.com/4406403/38225144-c51f4cf6-36f3-11e8-97c5-d6c83f9a6681.png)

Playing the announcement should resume the radio afterwards without having to to set playing to true. If for any reason this would not work (bug) then setting playing to true will play again url2play.

**Comment by Marty56** [comment]
> Playing the announcement should resume the radio afterwards without having to to set playing to true. 

Exactly this is NOT working and was the original issue I have reported.

**Comment by angelnu** [comment]
Do you refer #30 ? The log there does not show that the adapter was playing when sayit was used.

I released a fix to the castv2-player library that should help to resume playing. I released yesterday to git a new version of the chromecast adapter (1.4.3) that uses the new version. Could you please test with it? If it does not work please attach a log that includes when you started the streaming with url2play, played the announcement and then the adapter failed to resume.

**Comment by Marty56** [comment]
I am currently traveling and will not be home soon please do not expect fast feedback, sorry.

**Comment by Kunibert-007** [comment]
I have the same error like @Marty56 : After an announcement I don't hear the source I played before. When I play a source like Spotify or TuneIn the value from "Url2play" is always http://192.168.x.xx:8082/state/sayit.0.tts.mp3. I use the latest version 2.2.0 and I have a Google Home Max.
