### ISSUE TITLE
google home adapter does not change volume using sayit

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.chromecast#30]
I have setup the sayit adapter to use a google home speaker.
the command  e.g. setStateDelayed('sayit.1.tts.text',"50;Test") plays the Text but does not change the volume.

**Comment by angelnu** [comment]
What version of the Chromecast Adapter are you using? Could you attach a log with both alerts set to debug? This way we can see where the volume gets lost.

**Comment by Marty56** [comment]
[log.txt](https://github.com/angelnu/ioBroker.chromecast/files/1737015/log.txt)

I am using chromecast Adapter V 1.4.1 and sati Adapter V 1.6.7.

**Comment by angelnu** [comment]
Could you please also test this with v 1.4.3? I updated to a new version of the castv2-player library that should address the ignored volume.

**Comment by incase** [comment]
We can't control volumns on our Google Home mini devices:
We get "Sorry, update for Badezimmer.player.volume not supported".
Looking at the code of the lib, I'm not sure why this could happen, as that name looks exactly like the name it should expect for the property, but it falls through to the "not supported" case anyhow?.
We are using your 2.0 release, BTW.

**Comment by DoraDeu** [comment]
I have the same situation. Using Google Home mini and the 2.0 version of the adapter.
When I try to change the volume the following message appears in the Log:

<Devicename> - Sorry, update for <Devicename>.player.volume not supported!
Is there a way that this will be fixed? I think this has been working in one of the previous versions.

**Comment by DoraDeu** [comment]
Is someone working on the issues or is this just the new situation that the volume of Google Home devices can´t be changed?

**Comment by nicox** [comment]
I am running into the same issue, if i use sayi.it and let tts say some thing, there i can change the volume, but i get the error message :
(60923) Wohnzimmer - Sorry, update for Wohnzimmer.player.volume not supported!
if i try to set the volume for an mp3 file which i write into chromecast.0.Wohnzimmer.player.url2play,

**Comment by maxpd1** [comment]
same here. loudness has no effect on newest version of sayit adapter and google home mini as speaker.

**Comment by Marty56** [comment]
Workaround:
1. Install one sayit Adapter instance and point it to "Browser". in Code Example this is instance "0"
2. use code
`                setState("sayit.0.tts.text","Test Text");
                setTimeout(function() {
                    setState("chromecast.0.<put name of your google speaker her>.player.url2play","http://<ip of your iobroker instance>:8082/state/sayit.0.tts.mp3" );
                },2000);
`
3. The time in the Timeout function is needed to have the sayit Command complete the creation of the mp3 file. 2 Seconds worked in my case.
