### ISSUE TITLE
Connection Lost to Video Chromecast - No Reconnect

### ISSUE THREAD

**Issue by siggi85** [iobroker-community-adapters/ioBroker.chromecast#40]
I am using one Chromecast, one Audio Chromecast and four Google Homes with this adapter. But the connection to the Chromecast get lost even when it is on and the chromecast module ist not reconnecting.
CHROMECASTNAME.status.connected : "false"
Just the restart of the chromecast instance is working to reconnect to the chromecast and let me control it again. The error occure nearly every day.

**Comment by angelnu** [comment]
Maybe a dup from #36

**Comment by siggi85** [comment]
This Chromecast is the only of my google devices which is not always on. After your explaining of reconnecting, maybe this is the problem? I thougt the Chromecast is broadcasting when going up and the chromcast adapter is receiving the broadcast and putting the device up.
I put the adapter on debug log level and will provide log when the error occure again.
Could be a dupplicate of [#36](url=https://github.com/angelnu/ioBroker.chromecast/issues/36).

**Comment by siggi85** [comment]
It seems to be the max Reconnect Threshold. (see the log below)
Is there a way to let the adapter hear the broadcast of the Chromecast when it is starting? I think apps like YouTube, Netflix and others do the same.

Log:
> 2019-01-01 23:01:36.034 - warn: chromecast.0 Wohnzimmer_Chromecast - Client error: Error: connect EHOSTUNREACH 192.168.1.170:8009
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-01-01 23:03:15.106 - warn: chromecast.0 Wohnzimmer_Chromecast - Client error: Error: connect EHOSTUNREACH 192.168.1.170:8009
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-01-01 23:04:55.170 - warn: chromecast.0 Wohnzimmer_Chromecast - Client error: Error: connect EHOSTUNREACH 192.168.1.170:8009
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-01-01 23:06:36.226 - warn: chromecast.0 Wohnzimmer_Chromecast - Client error: Error: connect EHOSTUNREACH 192.168.1.170:8009
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-01-01 23:08:18.306 - warn: chromecast.0 Wohnzimmer_Chromecast - Client error: Error: connect EHOSTUNREACH 192.168.1.170:8009
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2019-01-01 23:09:58.309 - warn: chromecast.0 Wohnzimmer_Chromecast - Max amount of reconnects reached - stay offline

**Comment by angelnu** [comment]
I added very a first draft to trigger reconnects when the chromecast device broadcast its availability via MDNS. If this triggers too many reconnects I could add code in the player to prevent the extra reconnections but let us first see if this solves your issue.

Please update to `https://github.com/angelnu/ioBroker.chromecast/tarball/reconnect`

**Comment by angelnu** [comment]
Btw: another way for you to trigger a reconnect is to write the device.connected state in ioBoker to true.

**Comment by siggi85** [comment]
> https://github.com/angelnu/ioBroker.chromecast/tarball/reconnect

I had installed version 2.0.0 and now i have 2.0.2. I will tell you if it fixes the problem.

**Comment by siggi85** [comment]
Oh sorry, my last answer was not saved. Sorry for let you waiting.
Unfortunately the problem is still present. When the chromecast is offline for too long he is not coming back. The connected object remains "false".

**Comment by angelnu** [comment]
@siggi85,

do you have a log from when this happened? Did you wait 10 minutes after turning on the device again? Some devices do not send a mDNS broadcast after coming online so the adapter only find they are back when it sends its mDNS query every 10 minutes.

I could easily make the interval for the mDNS query to be configurable if you could confirm that fixes the issue.

Also if you are turning your Chromecast power using iobroker you can also trigger the chromecast to reconnect by writing the state chromecast.0.<device name>.enabled to true. This should force the adapter to start trying to connect to the device again.

**Comment by siggi85** [comment]
I installed version 2.2.0 today and it seems to work. I will watch this the next days but for now I am happy. :)
