### ISSUE TITLE
player.play toggle does not wake up Chromecast

### ISSUE THREAD

**Issue by SirAdelholt** [iobroker-community-adapters/ioBroker.chromecast#49]
I do not know if this is an issue or just comes with the nature of things, but toggling the player.play toggle does not wake up the chromecast if it is in sleep mode. 
I would like to turn on my TV this way (over HDMI-CEC). Opening a Multicast connection over any app on my phone does wake up the device, just none of the toggles provided by ioBroker.chromecast.

Please let me know if you need additional info or if this is the wrong place to discuss this.

**Comment by angelnu** [comment]
does it wake up when you play a stream with url2play?

**Comment by SirAdelholt** [comment]
Sadly, no, it doesn´t.
