### ISSUE TITLE
Could not play: TypeError: Cannot read property 'mediaSessionId' of null chromecast.0

### ISSUE THREAD

**Issue by siggi85** [iobroker-community-adapters/ioBroker.chromecast#52]
Installed Version: 2.2.0
The adapter works well normally. But today I had a problem that the Chromecast did not respond to play command. A paused YT video was on screen. I solved it by restarting the adapter.
Log:
chromecast.0	2019-02-11 17:53:16.581	error	Wohnzimmer_Chromecast - Could not play: TypeError: Cannot read property 'mediaSessionId' of null
chromecast.0	2019-02-11 17:53:14.305	error	Wohnzimmer_Chromecast - Could not play: TypeError: Cannot read property 'mediaSessionId' of null
chromecast.0	2019-02-11 17:53:11.055	error	Wohnzimmer_Chromecast - Could not play: TypeError: Cannot read property 'mediaSessionId' of null

**Comment by siggi85** [comment]
I had the error again since yesterday. Doesn't matter weather it is YouTube or Netflix.

**Comment by angelnu** [comment]
With the latest version 2.2.3 I started Netflix and then went to iobroker to play a url with url2play. I am not able to repro the issue you see.

I scanned the code and the only reference to mediaSessionId would be in a library I use. For reporting this issue upstream I would need to indicate how to repro.

**Comment by siggi85** [comment]
I will report when it occures again. I do not know how to reproduce the error at the moment.

**Comment by Jey-Cee** [comment]
Problem tritt auf wenn man url2play setzt und anchsließend sofort play. 
Das liegt ziemlich Wahrscheinlich daran dass url2play sofort den Stream startet.
