### ISSUE TITLE
Feature request : Add capability to play text messages

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.chromecast#62]
As google home is a great alternative against Alexa (at least in NL as Amazon still does not have the NL langue set) it would be nice to have the capability to play a text message 

( equal to Alexa)

Currently only media files can be played, I assume just sending a text message which is read/spoken out by google can also work ?
( workaround by sayit is possible, but not easy to use for everyone)

**Comment by raintonr** [comment]
This can easily be achieved with the sayit adapter:

https://github.com/ioBroker/ioBroker.sayit

**Comment by DutchmanNL** [comment]
> This can easily be achieved with the sayit adapter:

as mentioned : 

> ( workaround by sayit is possible, but not easy to use for everyone)
