### ISSUE TITLE
Error playing playlist - Error: queueLoad failed

### ISSUE THREAD

**Issue by haselchen** [iobroker-community-adapters/ioBroker.chromecast#71]
After updating the JS controller to 2.2.8 I get this error message.
![Mini](https://user-images.githubusercontent.com/42101470/74045912-e5c15f00-49cd-11ea-9819-84dbfb5873b8.PNG)

I have different mp3 that I can play depending on the event. They are stored, for example, at http: //192.XXX.XX.XX: XXXX / sayit.0 / tts.userfiles / Biotonne.mp3
Everything worked wonderfully until the update.

**Comment by Brainbug01** [comment]
I have the same problems:

´´´

host.iobroker-vm | 2020-02-26 18:14:25.228 | info | stopInstance system.adapter.chromecast.0 (force=false, process=true)
-- | -- | -- | --
chromecast.0 | 2020-02-26 18:14:10.276 | error | (9892) Wohnzimmer - Could not play announcement: TypeError: Cannot read property 'send' of null
chromecast.0 | 2020-02-26 18:14:10.276 | error | at process._tickCallback (internal/process/next_tick.js:68:7)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at /opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:495:16
chromecast.0 | 2020-02-26 18:14:10.276 | error | at new Promise (<anonymous>)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at /opt/iobroker/node_modules/castv2-player/lib/persistentPlayer.js:504:26
chromecast.0 | 2020-02-26 18:14:10.276 | error | at DefaultMediaReceiver.queueLoad (/opt/iobroker/node_modules/castv2-client/lib/senders/default-media-receiver.js:50:24)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at fn.MediaController.queueLoad (/opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:146:8)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at fn.RequestResponseController.request (/opt/iobroker/node_modules/castv2-client/lib/controllers/request-response.js:34:8)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at fn.Controller.send (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:28:16)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at Channel.send (/opt/iobroker/node_modules/castv2/lib/channel.js:34:12)
chromecast.0 | 2020-02-26 18:14:10.276 | error | at Client.send (/opt/iobroker/node_modules/castv2/lib/client.js:128:11)
chromecast.0 | 2020-02-26 18:14:10.276 | error | (9892) Wohnzimmer - Error playing playlist - TypeError: Cannot read property 'send' of null
chromecast.0 | 2020-02-26 18:14:10.276 | info | (9892) Wohnzimmer - Try to play playlist with 1 items
´´´´

**Comment by angelnu** [comment]
Are you able to download the file directly from the sayit link you pasted?

Please also try to use the chromecast version in github since I had merged some fixes that have not gone in a n official version yet.

With everything updated I am able to play URLs but I do not have sayit installed at the moment to try that part

**Comment by haselchen** [comment]
Hi @angelnu 

This problem drives me crazy. After another update of the JS controller, I have error messages in the log again.
Chromecaster Adapter 2.3.1
Sayit Adapter 1.12.3

Downgrades did not solve the problem.

`<html><body>


chromecast.0 | 2021-12-04 12:25:30.555 | error | (1210) GoogleHomeMini - Could not play announcement: Error: queueLoad failed
-- | -- | -- | --
chromecast.0 | 2021-12-04 12:25:30.555 | error | at TLSSocket.<anonymous>  (/opt/iobroker/node_modules/castv2-player/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at PacketStreamWrapper.emit (events.js:314:20)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at PacketStreamWrapper.onpacket (/opt/iobroker/node_modules/castv2-player/node_modules/castv2/lib/client.js:81:10)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at Client.emit (events.js:326:22)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at Client.onmessage (/opt/iobroker/node_modules/castv2-player/node_modules/castv2/lib/channel.js:23:10)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at Channel.emit (events.js:314:20)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at Channel.onmessage  (/opt/iobroker/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/controller.js:16:10)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at fn.emit (events.js:326:22)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at fn.onmessage  (/opt/iobroker/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
chromecast.0 | 2021-12-04 12:25:30.555 | error | at /opt/iobroker/node_modules/castv2-player/node_modules/castv2-client/lib/controllers/media.js:149:23
chromecast.0 | 2021-12-04 12:25:30.555 | error | (1210) GoogleHomeMini - Error playing playlist - Error: queueLoad failed


</body>
</html>`

**Comment by Berchemer** [comment]
I also have such a message (Error: queueLoad failed) again 😢
ChromeCast-Adapter is v3.0.1 from Github and the device is a Google ChromeCast Audio.

Logfile says:
`2022-02-25 12:32:13.394 - error: chromecast.0 (2177882) Chromecast Audio - 1OG - Schlafzimmer - Error playing playlist - Error: queueLoad failed
at /opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:149:23
at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
at fn.emit (events.js:412:35)
at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10)
at Channel.emit (events.js:400:28)
at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10)
at Client.emit (events.js:412:35)
at PacketStreamWrapper.onpacket (/opt/iobroker/node_modules/castv2/lib/client.js:81:10)
at PacketStreamWrapper.emit (events.js:400:28)
at TLSSocket. (/opt/iobroker/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
2022-02-25 12:32:13.400 - error: chromecast.0 (2177882) Chromecast_Audio_-_1OG_-_Schlafzimmer - Cannot play file "http://1.168.0.16/Sounds/temp/google.tts.ad99133f-e224-460f-8a81-d9859c8ccef2.mp3": Error: queueLoad failed
2022-02-25 12:32:13.521 - error: chromecast.0 (2177882) 1OGSchlafzimmerSpeaker - Error playing playlist - Error: queueLoad failed
at /opt/iobroker/node_modules/castv2-client/lib/controllers/media.js:149:23
at fn.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/request-response.js:27:7)
at fn.emit (events.js:412:35)
at Channel.onmessage (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:16:10)
at Channel.emit (events.js:400:28)
at Client.onmessage (/opt/iobroker/node_modules/castv2/lib/channel.js:23:10)
at Client.emit (events.js:412:35)
at PacketStreamWrapper.onpacket (/opt/iobroker/node_modules/castv2/lib/client.js:81:10)
at PacketStreamWrapper.emit (events.js:400:28)
at TLSSocket. (/opt/iobroker/node_modules/castv2/lib/packet-stream-wrapper.js:28:16)
2022-02-25 12:32:13.522 - error: chromecast.0 (2177882) 1OGSchlafzimmerSpeaker - Cannot play file "http://1.168.0.16/Sounds/temp/google.tts.ad99133f-e224-460f-8a81-d9859c8ccef2.mp3": Error: queueLoad failed
`
