### ISSUE TITLE
Allow YouTube videos

### ISSUE THREAD

**Issue by thopark** [iobroker-community-adapters/ioBroker.chromecast#75]
This library seems to allow playing YouTube videos:
https://github.com/alxhotel/chromecast-api/blob/master/lib/device.js
Maybe the functionality could be integrated?

**Comment by raintonr** [comment]
Do you mean you would like the ability to initiate the playing of YouTube video on the device in question? If so, yes, I would love that too!

How do you envisage this working? Perhaps a new state is required under media? `playContent` or something? This could be a read/write state into which URLs could be set. If the URL happens to be a YouTube site then the video ID should be extracted and played. Have a look at how https://github.com/skorokithakis/catt works. Something like that?

**Comment by thopark** [comment]
Yes, that's exactly what I had in mind.

**Comment by raintonr** [comment]
Ah... actually there is already the `player.url2play` state so that needs updating to handle YouTube links correctly.

**Comment by angelnu** [comment]
I am not actively developing this plugin anymore - PRs are welcome.

The url2play handler is able to process special URLs so support for youtube could be added there.

FYI @GermanBluefox

**Comment by raintonr** [comment]
Yes. Still relevant.

**Comment by maxpd1** [comment]
Thank you @raintonr didn't saw this topic before.

But yes. Playing YouTubeMusic songs would also be a great thing. URL structure is known. But I have the feeling some kind of authentication function is missing.

**Comment by raintonr** [comment]
In a search for a working implementation have discovered neither of these two work:

https://github.com/xat/castv2-youtube
https://github.com/irfanhabib/youtube-castv2-client

However, this does work...

https://github.com/alxhotel/chromecast-api

... but looks like the IOB adapter would require a major re-write in order to use that.

I will look at a quick solution copying some of the code from the latter and see if that's workable.

**Comment by raintonr** [comment]
See PR #103

**Comment by maxpd1** [comment]
@raintonr did you test if it also works for YTM? 

But nevertheless yesterday I also booked Spotify for known reasons.

**Comment by raintonr** [comment]
> @raintonr did you test if it also works for YTM?

Sorry, but I detest YTM. From what I can tell the video IDs should be interchangeable but who knows with that junk.

**Comment by raintonr** [comment]
Fixed with #103.

**Comment by maxpd1** [comment]
Hi @raintonr 

does this fix mean, that we can also play videos on a home mini? (surely only the audio of them)

**Comment by raintonr** [comment]
Why don't you try it and tell us. I suspect not.
