### ISSUE TITLE
turn tv on / off with this adapter? 

### ISSUE THREAD

**Issue by mtoensing** [iobroker-community-adapters/ioBroker.chromecast#83]
When I use the google home app with my ccu and tell google to "switch tv on" or off it does that by using HDMI CEC. can this be done with this adapter?

![image](https://user-images.githubusercontent.com/136737/114274498-e9f86a80-9a1e-11eb-84e3-ef3a962fa8b3.png)

**Comment by raintonr** [comment]
AFAIK this adapter cannot be used to initiate a stream, and therefore turn on the TV. Would actually love to be able to do that.

I don't think you can turn off Chromecast devices either. Forgetting this adapter for a second, I can ask our Google home to stream something to the 'TV' (name of the Chromecast), but when I ask it to turn that device off it doesn't know how. Is this a limitation of Chromecast or am I doing something wrong?

However... what TV make/model do you have? We have a Sony Bravia and there is a separate ioBroker adapter for that and yes, that adapter is able to turn the TV on & off (among many other things).

**Comment by mtoensing** [comment]
No thats not how my CCU works. I can open my Google Home App on iOS and tell Google "turn on tv" or "turn off tv" this works with HDMI CEC. I have a Samsung TV and it is not possible to turn it on/off via an. API. But the chromecast can (like a PS4/5, too via CEC). And I thought your adapter can use that.

**Comment by raintonr** [comment]
This isn't my adapter, but still ;)

Our Bravia TV (built in Chromecast device) appears not to support this. I can actually (just tried) to tell it "Turn on the TV" and that works, but "Turn off the TV" doesn't and Google Assistant says consult the device manual to see if this is supported.

I looked at the https://github.com/angelnu/castv2-player library this adapter uses and doesn't appear to be any reference to power functions in there. If you can find info on the Chromecast API and it's HDMI CEC functions then maybe it can be added though?
