### ISSUE TITLE
Could not play announcement: TypeError: Cannot read property 'launch' of null

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.chromecast#93]
Hi, 

most of the times, not always, if I want to play a notification in an chromecast group I get above message in the log. If I switch to a single google home or chromecast device its working. In the example we have sayit 3 which is the group and sayit 2 which is a dedicated chromecast.

`
<html>
<body>

chromecast.0 | 2021-05-14 16:21:36.983 | info | (2441) Wohnzimmer - set volume to 50
-- | -- | -- | --
chromecast.0 | 2021-05-14 16:21:36.921 | info | (2441) Wohnzimmer - Finished playing announcement
chromecast.0 | 2021-05-14 16:21:30.707 | info | (2441) Wohnzimmer - Playing playlist with 1 items
chromecast.0 | 2021-05-14 16:21:30.706 | info | (2441) Wohnzimmer - Playing - http://192.168.178.30:8082/state/sayit.2.tts.mp3
chromecast.0 | 2021-05-14 16:21:30.704 | info | (2441) Google Home Wohnzimmer - Playing - http://192.168.178.30:8082/state/sayit.2.tts.mp3
chromecast.0 | 2021-05-14 16:21:29.620 | info | (2441) Wohnzimmer - set volume to 70
chromecast.0 | 2021-05-14 16:21:29.589 | info | (2441) Wohnzimmer - Try to play playlist with 1 items
chromecast.0 | 2021-05-14 16:21:29.588 | info | (2441) Wohnzimmer - Closing mediaInfo
chromecast.0 | 2021-05-14 16:21:29.533 | info | (2441) Wohnzimmer - Try to play url - http://192.168.178.30:8082/state/sayit.2.tts.mp3
chromecast.0 | 2021-05-14 16:21:29.533 | info | (2441) Wohnzimmer - Try to play announcement - "http://192.168.178.30:8082/state/sayit.2.tts.mp3"
chromecast.0 | 2021-05-14 16:21:29.533 | info | (2441) Wohnzimmer - Player joint
chromecast.0 | 2021-05-14 16:21:29.532 | info | (2441) Wohnzimmer - Connected player
chromecast.0 | 2021-05-14 16:21:29.532 | info | (2441) Wohnzimmer - Default player lauched
chromecast.0 | 2021-05-14 16:21:29.532 | info | (2441) Wohnzimmer - Connected player
chromecast.0 | 2021-05-14 16:21:29.530 | info | (2441) Wohnzimmer - Try to join player
chromecast.0 | 2021-05-14 16:21:29.527 | info | (2441) Google Home Wohnzimmer - Player joint
chromecast.0 | 2021-05-14 16:21:29.527 | info | (2441) Google Home Wohnzimmer - Connected player
chromecast.0 | 2021-05-14 16:21:29.526 | info | (2441) Google Home Wohnzimmer - Try to join player
chromecast.0 | 2021-05-14 16:21:27.262 | info | (2441) Wohnzimmer - Try to launch default player
sayit.2 | 2021-05-14 16:21:27.257 | info | (2599) Set "chromecast.0.Wohnzimmer.player.announcement to {"url":"http://192.168.178.30:8082/state/sayit.2.tts.mp3","volume":70}
sayit.2 | 2021-05-14 16:21:27.252 | info | (2599) saying: Die heutige Indizenz im Bundesland liegt bei 102. Im Landkreis soundso sind es 131
chromecast.0 | 2021-05-14 16:21:22.396 | error | (2441) Iobrokergruppe - Could not play announcement: TypeError: Cannot read property 'launch' of null
chromecast.0 | 2021-05-14 16:21:22.396 | info | (2441) Iobrokergruppe - Try to launch default player
sayit.3 | 2021-05-14 16:21:22.350 | info | (2642) Set "chromecast.0.Iobrokergruppe.player.announcement to {"url":"http://192.168.178.30:8082/state/sayit.3.tts.mp3","volume":70}
sayit.3 | 2021-05-14 16:21:22.301 | info | (2642) saying: Achso, und außerdem ist Müllabfuhr von ,,,der schwarzen Tonne
chromecast.0 | 2021-05-14 16:21:20.656 | info | (2441) Wohnzimmer - Detached player
chromecast.0 | 2021-05-14 16:21:20.655 | info | (2441) Google Home Wohnzimmer - Detached player
chromecast.0 | 2021-05-14 16:21:12.347 | error | (2441) Iobrokergruppe - Could not play announcement: TypeError: Cannot read property 'launch' of null
chromecast.0 | 2021-05-14 16:21:12.346 | info | (2441) Iobrokergruppe - Try to launch default player
sayit.3 | 2021-05-14 16:21:12.300 | info | (2642) Set "chromecast.0.Iobrokergruppe.player.announcement to {"url":"http://192.168.178.30:8082/state/sayit.3.tts.mp3","volume":70}
sayit.3 | 2021-05-14 16:21:12.254 | info | (2642) saying: Guten Morgen. Wir bekommen heute Höchsttemperaturen von 16 Grad und Teils bewölkt mit leichtem Regen
javascript.0 | 2021-05-14 16:20:45.798 | info | (1729) script.js.Sprachbefehle.Rolläden_IFTTT: registered 3 subscriptions and 0 schedules
javascript.0 | 2021-05-14 16:20:45.779 | info | (1729) Start javascript script.js.Sprachbefehle.Rolläden_IFTTT
javascript.0 | 2021-05-14 16:20:45.769 | info | (1729) Stop script script.js.Sprachbefehle.Rolläden_IFTTT

</body>
</html>`

This is my blockly which triggers the texts:

![2021-05-14 16_31_43-javascript - ioBroker](https://user-images.githubusercontent.com/15956503/118285934-41806f00-b4d2-11eb-9222-e9a92d8ec6ed.png)

**Comment by Hamsterrennen** [comment]
same issue here

**Comment by pjo12345** [comment]
I have the same problem.

**Comment by Jey-Cee** [comment]
Please test v3.0.1 from Github.
