### ISSUE TITLE
Chromecast adapter in restart loop (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.chromecast#95]
Hi,

I updated my iobroker and also Linux and now I have a restart loop in chromecast. Do you have an idea how to fix this?

`
<html>
<body>

host.iobroker | 2021-05-15 12:46:44.767 | warn | Do not restart adapter system.adapter.chromecast.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2021-05-15 12:46:44.767 | info | Restart adapter system.adapter.chromecast.0 because enabled
host.iobroker | 2021-05-15 12:46:44.765 | error | instance system.adapter.chromecast.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
chromecast.0 | 2021-05-15 12:46:44.141 | warn | (20452) Terminated (UNCAUGHT_EXCEPTION): Without reason
chromecast.0 | 2021-05-15 12:46:44.140 | info | (20452) terminating
chromecast.0 | 2021-05-15 12:46:44.139 | info | (20452) Unload completed sucesfully
chromecast.0 | 2021-05-15 12:46:44.139 | info | (20452) Google Home Wohnzimmer - client disconnected
chromecast.0 | 2021-05-15 12:46:44.138 | info | (20452) Küche - client disconnected
chromecast.0 | 2021-05-15 12:46:44.137 | info | (20452) Küche - Detached player
chromecast.0 | 2021-05-15 12:46:44.137 | info | (20452) Küche - Detached player
chromecast.0 | 2021-05-15 12:46:44.135 | info | (20452) Iobrokergruppe - client disconnected
chromecast.0 | 2021-05-15 12:46:44.135 | info | (20452) Badezimmer - client disconnected
chromecast.0 | 2021-05-15 12:46:44.134 | info | (20452) Chromecast Ultra - client disconnected
chromecast.0 | 2021-05-15 12:46:44.133 | info | (20452) Chromecast Ultra - Detached player
chromecast.0 | 2021-05-15 12:46:44.132 | info | (20452) Chromecast Ultra - Detached player
chromecast.0 | 2021-05-15 12:46:44.131 | info | (20452) Kueche - client disconnected
chromecast.0 | 2021-05-15 12:46:44.130 | info | (20452) Kueche - Detached player
chromecast.0 | 2021-05-15 12:46:44.129 | info | (20452) Kueche - Detached player
chromecast.0 | 2021-05-15 12:46:44.125 | info | (20452) Destroying chromecast scanner
chromecast.0 | 2021-05-15 12:46:44.125 | info | (20452) Unload triggered
chromecast.0 | 2021-05-15 12:46:42.787 | info | (20452) Kueche - Player joint
chromecast.0 | 2021-05-15 12:46:42.786 | info | (20452) Kueche - Connected player
chromecast.0 | 2021-05-15 12:46:42.784 | info | (20452) Kueche - Try to join player
chromecast.0 | 2021-05-15 12:46:42.781 | info | (20452) Chromecast Ultra - Player joint
chromecast.0 | 2021-05-15 12:46:42.779 | info | (20452) Chromecast Ultra - Connected player
chromecast.0 | 2021-05-15 12:46:42.777 | info | (20452) Chromecast Ultra - Try to join player
chromecast.0 | 2021-05-15 12:46:42.773 | info | (20452) Küche - Player joint
chromecast.0 | 2021-05-15 12:46:42.771 | info | (20452) Küche - Connected player
chromecast.0 | 2021-05-15 12:46:42.765 | info | (20452) Küche - Try to join player
chromecast.0 | 2021-05-15 12:46:42.731 | info | (20452) Küche - Connected client
chromecast.0 | 2021-05-15 12:46:42.724 | info | (20452) Google Home Wohnzimmer - Connected client
chromecast.0 | 2021-05-15 12:46:42.718 | info | (20452) Iobrokergruppe - Connected client
chromecast.0 | 2021-05-15 12:46:42.698 | info | (20452) Badezimmer - Connected client
chromecast.0 | 2021-05-15 12:46:42.692 | info | (20452) Kueche - Connected client
chromecast.0 | 2021-05-15 12:46:42.685 | info | (20452) Chromecast Ultra - Connected client
chromecast.0 | 2021-05-15 12:46:42.607 | error | (20452) extension not loaded yet
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Object.onceWrapper (events.js:420:28)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at TLSSocket.<anonymous> (/opt/iobroker/node_modules/castv2/lib/client.js:40:10)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Client.emit (events.js:314:20)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Object.onceWrapper (events.js:420:28)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Client.<anonymous> (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:59:21)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at fn.ConnectionController.connect (/opt/iobroker/node_modules/castv2-client/lib/controllers/connection.js:28:8)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at fn.Controller.send (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:28:16)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Channel.send (/opt/iobroker/node_modules/castv2/lib/channel.js:34:12)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Client.send (/opt/iobroker/node_modules/castv2/lib/client.js:127:25)
chromecast.0 | 2021-05-15 12:46:42.607 | error | at Object.serialize (/opt/iobroker/node_modules/castv2/lib/proto.js:29:15)
chromecast.0 | 2021-05-15 12:46:42.607 | error | (20452) Error: extension not loaded yet
chromecast.0 | 2021-05-15 12:46:42.605 | error | (20452) uncaught exception: extension not loaded yet
chromecast.0 | 2021-05-15 12:46:42.598 | error | (20452) extension not loaded yet
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Object.onceWrapper (events.js:420:28)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at TLSSocket.<anonymous> (/opt/iobroker/node_modules/castv2/lib/client.js:40:10)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Client.emit (events.js:314:20)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Object.onceWrapper (events.js:420:28)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Client.<anonymous> (/opt/iobroker/node_modules/castv2-client/lib/senders/platform.js:59:21)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at fn.ConnectionController.connect (/opt/iobroker/node_modules/castv2-client/lib/controllers/connection.js:28:8)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at fn.Controller.send (/opt/iobroker/node_modules/castv2-client/lib/controllers/controller.js:28:16)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Channel.send (/opt/iobroker/node_modules/castv2/lib/channel.js:34:12)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Client.send (/opt/iobroker/node_modules/castv2/lib/client.js:127:25)
chromecast.0 | 2021-05-15 12:46:42.597 | error | at Object.serialize (/opt/iobroker/node_modules/castv2/lib/proto.js:29:15)
chromecast.0 | 2021-05-15 12:46:42.597 | error | (20452) Error: extension not loaded yet
chromecast.0 | 2021-05-15 12:46:42.595 | error | (20452) uncaught exception: extension not loaded yet
chromecast.0 | 2021-05-15 12:46:41.946 | info | (20452) starting. Version 2.3.1 in /opt/iobroker/node_modules/iobroker.chromecast, node: v12.22.1, js-controller: 3.2.16
host.iobroker | 2021-05-15 12:46:39.879 | info | instance system.adapter.chromecast.0 started with pid 20452
host.iobroker | 2021-05-15 12:46:09.847 | info | Restart adapter system.adapter.chromecast.0 because enabled

</body>
</html>`

**Comment by dfoerster79** [comment]
Same Problem

**Comment by Duggles1301** [comment]
Same Problem here!

**Comment by M1cS0w** [comment]
Hi, I got this problem too. A restart loop should be a problem, and I have to check the protocol, but there are no problems with restarts, only while restarting the adapter, to fill in new devices!?
